@startuml

'https://plantuml.com/use-case-diagram
skinparam actorStyle awesome

skinparam usecase {
    BackgroundColor PapayaWhip
    BorderColor Black
}

skinparam Actor {
    BackgroundColor Green
    BorderColor Black
}

skinparam Arrow {
    Color Black
}

:Admin:
:User:

(Person CRUD)
(Movie CRUD)
(User CRUD)
(Review CRUD)
(Modify list of favorite movies) as fav
(Get movie/movies) as view

(Get movie\n recommendations) as recommend

(Login)
(Logout)

Admin -down->(Review CRUD)
Admin -right-> (User CRUD)
Admin -left-> (Person CRUD)
Admin -up-> (Movie CRUD)
User --> (User CRUD)
User --> (Review CRUD)
User --> fav
User -up-> view
(User CRUD) --> fav : Includes
(Movie CRUD) -> view : Includes

User --> recommend

User --> (Login)
User --> (Logout)


'Generalization
Admin -> User : Specifies

note right of User
    Can create his own profile, modify it and delete it.
    Can create, modify, delete his own reviews.
    Can read reviews created by any user.
    Can search for a specific movie/movies.
    Can filter and order list of movies.
end note

@enduml